version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"     # Web UI
      - "50000:50000"   # JNLP agent port
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Access to host's Docker
    user: root  # Required to access docker.sock
    environment:
      JAVA_OPTS: "-Duser.timezone=Asia/Jakarta"
    restart: unless-stopped

volumes:
  jenkins_home:
